server:
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 20s

jwt:
  secret: ${JWT_SECRET_KEY}
  exp:
    access: ${JWT_EXP_ACCESS}
    refresh: ${JWT_EXP_REFRESH}
