server:
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 20s

jwt:
  secret: ${JWT_SECRET_KEY}
  access-exp: ${JWT_EXP_ACCESS}
  refresh-exp: ${JWT_EXP_REFRESH}

cloud:
  aws:
    region:
      static: ${AWS_S3_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS:s3_access}
      secret-key: ${AWS_S3_SECRET:s3_secret}

aws:
  s3:
    url: ${AWS_S3_URL:https://}
    bucket: ${AWS_S3_BUCKET:bucket}
    profile-folder: ${AWS_S3_PROFILE_FOLDER:pro-image/}
    preview-folder: ${AWS_S3_PREVIEW_FOLDER:pre-image/}
  ses:
    access-key: ${AWS_SES_ACCESS:ses_access}
    secret-key: ${AWS_SES_SECRET:ses_secret}
    region: ${AWS_SES_REGION:ap-northeast-2}

auth:
  auth-time: ${AUTH_TIME}
  limit-time: ${LIMIT_TIME}

sms:
  key: ${SMS_KEY}
  secret: ${SMS_SECRET}
  phone-number: ${SENDER_PHONE_NUMBER}